[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
asse-manager = "CMwajZwWza6yrcai3S55wZRzKamjMvKA1XAZJEFxTbzu"
asset-manager = "DXcb3bPmKdYJdQJ2cAKzWDexhgLG8d5RxTWCcXcAJAV4"
balanced-dollar = "JD9VQBYWE2wm2QyJdRENT5fUnXSyn6ACPVmtqa3bTQFF"
xcall_manager = "GQzwcViCnhHGLjtg62FfNrhfiEpwiVQdHgTaTka8ozQX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.js"
